### ISSUE TITLE
motion with cmd_vel

### ISSUE THREAD

**Issue by ryuichiueda** [rt-net/raspimouse_sim#2]
The robot should not stop after subscribing cmd_vel. The values should be explicitly given when the robot stops. 

Or should I fix the side of the actual robot? In the viewpoint of safety, I also think that the robot should stop when subscribing of cmd_vel is stopped.

**Comment by Tiryoh** [comment]
@ryuichiueda 
Do you mean that the robot should keep moving at the same speed forever after subscribing cmd_vel once?


That is not the way declared [here](http://docs.ros.org/api/geometry_msgs/html/msg/Twist.html). I don't think it is a good idea to use cmd_vel in a different way as a same name.


I think it's better to fix the controller of the actual robot, or use another command.


"raspimouse_sim" uses [diff_drive_controller](http://wiki.ros.org/diff_drive_controller) to move the wheel.  "diff_drive_controller" subscribes geometry_msgs/Twist message, that are defined [here](http://docs.ros.org/api/geometry_msgs/html/msg/Twist.html).


When this controller subscribes geometry_msgs/Twist message, the wheels rotate for 1sec.  As shown below, I think it is better to use `-r` option for `rostopic pub`.


> You may have noticed that the turtle has stopped moving; this is because the turtle requires a steady stream of commands at 1 Hz to keep moving. We can publish a steady stream of commands using rostopic pub -r command:
>
> For ROS Hydro and later,
>
> `$ rostopic pub /turtle1/cmd_vel geometry_msgs/Twist -r 1 -- '[2.0, 0.0, 0.0]' '[0.0, 0.0, -1.8]'`


http://wiki.ros.org/fr/ROS/Tutorials/UnderstandingTopics

**Comment by ryuichiueda** [comment]
OK. I implement the turttle bot's behavior. It will be the best way.

**Comment by Tiryoh** [comment]
Thank you.
