### ISSUE TITLE
ブランチ構成の変更

### ISSUE THREAD

**Issue by ShotaAk** [rt-net/raspimouse_sim#28]
kinetic-develブランチをmelodic-develブランチをmasterブランチに統合して、メンテナンスのしやすさを向上させる。

**Comment by ShotaAk** [comment]
修正が必要なページ
- https://github.com/rt-net/raspimouse_sim/wiki
- https://github.com/rt-net/raspimouse_sim/wiki/quickstart
  - ブランチが減るのでインストールスクリプトの修正が必要
  - https://git.io/raspimouse-sim-installer
- https://github.com/rt-net/raspimouse_sim/wiki/how_to_install_simulator_xenial

**Comment by Tiryoh** [comment]
# 背景

2020年2月現在、`rpim_book_version`ブランチとROSのディストリビューションごとの'[ros distribution]-devel'で開発している。
KineticとMelodic用のROSパッケージをそれぞれのブランチで開発をしており、Indigo用ROSパッケージについてはindigo-branchに最終更新時のデータだけ残している。

機能追加や不具合修正の際に複数のブランチでそれぞれ作業をすることは手間がかかるだけではなく、ミスの原因となり得る。

# 提案

以下で説明するようなブランチ構成に変更することでメンテナンス性の向上を図る。

## ブランチ構成
### 現状
* `rpim_book_version`ブランチ
    * ラズパイマウス本用
* indigo-devel
    * ROS Indigo用（更新停止）
* kinetic-devel
    * ROS Kinetic用（開発用）
* melodic-devel
    * ROS Melodic用（開発用）

### 提案
* master
    * メインで開発に用いるブランチ
* `rpim_book_version`ブランチ
    * ラズパイマウス本用（現状維持）
* indigo-devel
    * ROS Indigo用（更新停止）（現状維持）
* kinetic-devel
    * ROS Kinetic用
    * masterブランチの内容を定期的にmergeする
    * 安定して使えるバージョンはこちらとし、今後debianパッケージをリリースすることがあればこちらのブランチを参照する
* melodic-devel
    * ROS Melodic用
    * masterブランチの内容を定期的にmergeする
    * 安定して使えるバージョンはこちらとし、今後debianパッケージをリリースすることがあればこちらのブランチを参照する

**Comment by Tiryoh** [comment]
wikiに移してこちらはクローズします。
