### ISSUE TITLE
with the device files

### ISSUE THREAD

**Issue by ryuichiueda** [rt-net/raspimouse_sim#3]
To actualize the perfect compatibility, the simulated robot should send and receive its data. But it will be constructed as another simulator.

**Comment by Tiryoh** [comment]
@ryuichiueda 
I agree with your opinion, that we should use device files for controlling sensors, motors to actualize compatibility "perfectly".

Unfortunately, the default controller "diff_drive_controller" don't subscribe cmd_vel via device files.  
I think the important thing for this simulator is to subscribe/publish ROS topic like the actual robot and [other robots](http://wiki.ros.org/Robots), so I am planning to use the default controller, for now.

**Comment by ryuichiueda** [comment]
I understand. Someone would try this issue based on your nice work. We should find someone...
