### ISSUE TITLE
バーチャルデバイスファイル機能をオプションにする

### ISSUE THREAD

**Issue by Tiryoh** [rt-net/raspimouse_sim#30]
現在、テキストファイルを仮想のデバイスファイルとして`/dev/`以下に作成して、実機のロボットと同じように`raspimouse_ros_2`パッケージを経由してセンサやモータへアクセスしている。
ほかのロボットのシミュレータと同様に、本シミュレータにはROSのインターフェースのみ（`/cmd_vel`、`/lightsensors`などのトピックの配信/購読）を用意し、仮想のデバイスファイルはオプションとして分割して提供する。この場合、`raspimouse_ros_2`なしでもROSトピックのやりとりが可能となる。
https://github.com/rt-net/raspimouse_sim/blob/eedb23ee3d8f0ac25ffa4754880c1487317c057d/raspimouse_control/scripts/virtual_led_sensors.py#L23-L26

**Comment by ShotaAk** [comment]
良いと思います。
デバイスファイルあり・なしのどちらをデフォルトにするか検討が必要です。

**Comment by ShotaAk** [comment]
パッケージ内でraspimouse_ros_2に依存しているところ確認しましたが、ありませんでした。

**Comment by Tiryoh** [comment]
よくあるROSのロボットのシミュレータのようにROSのインターフェース（/cmd_velなど）をデフォルトの操作インターフェースとして、バーチャルデバイスファイルの操作インターフェースはオプションにする方が気軽に試せると思うので（root権限で/dev/以下を書き換えるのは抵抗ある人もいると思います）変更します。後方互換性がなくなる変更なので次はバージョン1.0.0としたいと思います。
https://github.com/rt-net/raspimouse_sim/milestone/1

**Comment by Tiryoh** [comment]
#53 にてデフォルトではデバイスファイルなしとしました。
