### ISSUE TITLE
Which is main branch master or indigo-devel?

### ISSUE THREAD

**Issue by youtalk** [rt-net/raspimouse_sim#4]
I found a problem with two branches, master and indigo-devel.

- https://github.com/rt-net/raspimouse_sim/tree/master
- https://github.com/rt-net/raspimouse_sim/tree/indigo-devel

The result of following command is no difference.

~~~
git diff master indigo-devel
~~~

Which I use the target branch to pull a future request?

**Comment by Tiryoh** [comment]
Thanks for asking, @youtalk.
Please use 'indigo-devel' branch.
I'm planning to use '[ros distribution]-devel' branch as the main branch.

**Comment by youtalk** [comment]
@Tiryoh Thank you. I'll use the indigo-devel branch.
