### ISSUE TITLE
odom.rvizについて

### ISSUE THREAD

**Issue by shu-rt** [rt-net/raspimouse_sim#58]
# 現状の問題点

odom.rvizにラズパイマウスと関係ないステレオカメラのトピックが追加されている。  
また、laser scanのトピックが追加されていないので追加したい。

# 改善案

pointcloud2を消去して、laserscanを足す。

**Comment by shu-rt** [comment]
ラベルの付け方が正しいかはわかりませんが….  
後ほど設定変更してプルリクを出したいと思っています。

**Comment by Tiryoh** [comment]
https://github.com/rt-net/raspimouse_sim/pull/56 にて追加したものです。

> ステレオカメラのトピックが追加されている。

https://github.com/rt-net/jnmouse_sim/blob/master/jnmouse_gazebo/launch/config/odom.rviz よりコピーしてきたのでそのままになっていました :sweat_smile: 

迷路などLiDARを搭載していないモデルで`keyboard_teleop.launch`を起動するケース（`raspimouse_with_samplemaze.launch`）も考えられるので、
`/scan`トピックがない場合でもLaserScanでエラーが表示されないことを確認する必要がありそうです。

**Comment by shu-rt** [comment]
なるほど！  
別の.rvizファイルを用意して切り分けるか、まとめるか…  
`lidar:=true`とか付け足すのめんどいかな

**Comment by Tiryoh** [comment]
> # What does this implement/fix?
> teleopをするためのlaunchファイル実行時にRVizでオドメトリを可視化できるようにします。
> ![Screenshot from 2020-11-05 13-31-07](https://user-images.githubusercontent.com/3256629/98198014-5ac8c180-1f6b-11eb-9d2e-85a93af1664d.png)
> 

PointCloud2と同じであればトピックがなくてもエラーが出ないかもしれません。
`/scan`トピックがないとエラーが出る場合はLaserScanの表示はデフォルトオフになるようにお願いします。

**Comment by shu-rt** [comment]
大丈夫そうです〜！手動でLaserScanを追加して、`/scan`トピックを受け取るように設定しましたが、特にエラーは表示されませんでした。
![Screen Shot 2021-07-29 at 17 36 55](https://user-images.githubusercontent.com/55081284/127460380-5c363d46-c653-4bc0-a2a1-486df17b14e4.png)
